// STATE TYPE
export const HEADER_CLICKED = 'HEADER_CLICKED';
export const HEADER_ERROR = 'HEADER_ERROR';
export const HEADER_SEARCH = 'HEADER_SEARCH';

export const CATEGORY_FETCHING = 'CATEGORY_FETCHING';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';

export const RECOMMEND_FETCHING = 'RECOMMEND_FETCHING';
export const RECOMMEND_ERROR = 'RECOMMEND_ERROR';
export const RECOMMEND_SUCCESS = 'RECOMMEND_SUCCESS';

export const ADVERTISEMENT_FETCHING = 'ADVERTISEMENT_FETCHING';
export const ADVERTISEMENT_ERROR = 'ADVERTISEMENT_ERROR';
export const ADVERTISEMENT_SUCCESS = 'ADVERTISEMENT_SUCCESS';

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_DIALOG_DISPLAY = 'LOGIN_DIALOG_DISPLAY';
export const LOGIN_DIALOG_CLOSE = 'LOGIN_DIALOG_CLOSE';
export const LOGIN_INITIALIZE = 'LOGIN_INITIALIZE';

export const REGISTER_INITIALIZE = 'REGISTER_INITIALIZE';
export const REGISTER_REQUESTING = 'REGISTER_REQUESTING';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_DIALOG_DISPLAY = 'REGISTER_DIALOG_DISPLAY';
export const REGISTER_DIALOG_CLOSE = 'REGISTER_DIALOG_CLOSE';

export const ITEMLIST_FETCHING = 'ITEMLIST_FETCHING';
export const ITEMLIST_ERROR = 'ITEMLIST_ERROR';
export const ITEMLIST_SUCCESS = 'ITEMLIST_SUCCESS';

export const BUY_FETCHING = 'BUY_FETCHING';
export const BUY_ERROR = 'BUY_ERROR';
export const BUY_FETCH_SUCCESS = 'BUY_FETCH_SUCCESS';
export const BUY_DIALOG_DISPLAY = 'BUY_DIALOG_DISPLAY';
export const BUY_DIALOG_CLOSE = 'BUY_DIALOG_CLOSE';

// Constant value
export const REGISTER_STATUS_SUCCESS = 201;

// API
export const HOST = 'http://localhost:8080'

// View
export const API_SERVICE = HOST + '/api/view';
export const INIT_API = API_SERVICE + '/init';
export const CATEGORY_API = API_SERVICE + '/category';
export const RECOMMEND_API = API_SERVICE + '/recommend';
export const ADVERTISEMENT_API = API_SERVICE + '/advertisement';
export const ITEMLIST_API = API_SERVICE + '/itemlist';
export const BUY_API = API_SERVICE + '/buy';

// Authentication
export const API_AUTHEN_SERVICE = HOST + '/authen'
export const REQUESTLOGIN_API = API_AUTHEN_SERVICE + '/login';
export const REQUESTREGISTER_API = API_AUTHEN_SERVICE + '/register';